import sys, os
from PyQt5.QtWidgets import QMainWindow, QAction, QMenu, QApplication, QFileDialog 
import subprocess

class Example(QMainWindow):

    def __init__(self):
        super().__init__()

        self.initUI()

    def initUI(self): 
        menubar = self.menuBar()
        fileMenu = menubar.addMenu('File')

        impMenu = QMenu('Import', self)
        impAct = QAction('Import mail', self)
        impMenu.addAction(impAct)

        newAct = QAction('New', self)
        uploadAct = QAction('Upload', self)
        uploadAct.triggered.connect(self.openFileNameDialog)
        


        fileMenu.addAction(newAct)
        fileMenu.addAction(uploadAct)
                
        fileMenu.addMenu(impMenu) 
        
        self.setGeometry(300, 300, 300, 200)
        self.setWindowTitle('Submenu')
        self.show()
    
    def openFileNameDialog(self):
        options = QFileDialog.Options()
        options |= QFileDialog.DontUseNativeDialog
        fileName, _ = QFileDialog.getOpenFileName(self,"QFileDialog.getOpenFileName()", "","All Files (*);;Python Files (*.py)", options=options)
        if fileName:
            print(fileName)
    
    def openFileNamesDialog(self):
        options = QFileDialog.Options()
        options |= QFileDialog.DontUseNativeDialog
        files, _ = QFileDialog.getOpenFileNames(self,"QFileDialog.getOpenFileNames()", "","All Files (*);;Python Files (*.py)", options=options)
        if files:
            print(files)
    
    def saveFileDialog(self):
        options = QFileDialog.Options()
        options |= QFileDialog.DontUseNativeDialog
        fileName, _ = QFileDialog.getSaveFileName(self,"QFileDialog.getSaveFileName()","","All Files (*);;Text Files (*.txt)", options=options)
        if fileName:
            print(fileName)
  

def main():
    app = QApplication(sys.argv)
    ex = Example()
    sys.exit(app.exec_())


if __name__ == '__main__':
    main()
 #############################################
    
    # -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MossInterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(574, 492)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 331, 151))
        self.groupBox.setObjectName("groupBox")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(10, 20, 81, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(180, 20, 111, 20))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(120, 20, 47, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 47, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(126, 100, 91, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 81, 20))
        self.label_4.setObjectName("label_4")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setGeometry(QtCore.QRect(210, 60, 70, 20))
        self.checkBox.setObjectName("checkBox")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(50, 60, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(90, 100, 21, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEdit.setGeometry(QtCore.QRect(210, 100, 111, 41))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.ExtractedFiles = QtWidgets.QScrollArea(self.centralwidget)
        self.ExtractedFiles.setGeometry(QtCore.QRect(370, 30, 191, 411))
        self.ExtractedFiles.setWidgetResizable(True)
        self.ExtractedFiles.setObjectName("ExtractedFiles")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 189, 409))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.listWidget = QtWidgets.QListWidget(self.scrollAreaWidgetContents_2)
        self.listWidget.setGeometry(QtCore.QRect(0, 0, 191, 411))
        self.listWidget.setObjectName("listWidget")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.scrollAreaWidgetContents_2)
        self.verticalScrollBar.setGeometry(QtCore.QRect(170, 0, 15, 411))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.ExtractedFiles.setWidget(self.scrollAreaWidgetContents_2)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(380, 10, 81, 20))
        self.label_5.setObjectName("label_5")
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea.setGeometry(QtCore.QRect(10, 160, 351, 281))
        self.mdiArea.setObjectName("mdiArea")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 140, 47, 20))
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 574, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSubmission = QtWidgets.QMenu(self.menubar)
        self.menuSubmission.setObjectName("menuSubmission")
        self.menuReports = QtWidgets.QMenu(self.menubar)
        self.menuReports.setObjectName("menuReports")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExtract_files = QtWidgets.QAction(MainWindow)
        self.actionExtract_files.setObjectName("actionExtract_files")
        self.actionExtract_Files = QtWidgets.QAction(MainWindow)
        self.actionExtract_Files.setObjectName("actionExtract_Files")
        self.actionGenerate_Reports = QtWidgets.QAction(MainWindow)
        self.actionGenerate_Reports.setObjectName("actionGenerate_Reports")
        self.actionExtract_Files_2 = QtWidgets.QAction(MainWindow)
        self.actionExtract_Files_2.setObjectName("actionExtract_Files_2")
        self.actionSave_Report = QtWidgets.QAction(MainWindow)
        self.actionSave_Report.setObjectName("actionSave_Report")
        self.menuFile.addAction(self.actionExtract_Files)
        self.menuFile.addAction(self.actionExtract_Files_2)
        self.menuReports.addAction(self.actionGenerate_Reports)
        self.menuReports.addAction(self.actionSave_Report)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSubmission.menuAction())
        self.menubar.addAction(self.menuReports.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MOSS UI"))
        self.groupBox.setTitle(_translate("MainWindow", "Submission Specifications"))
        self.lineEdit.setText(_translate("MainWindow", "Userid"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Select Language"))
        self.comboBox.setItemText(1, _translate("MainWindow", "C"))
        self.comboBox.setItemText(2, _translate("MainWindow", "C++"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Java"))
        self.comboBox.setItemText(4, _translate("MainWindow", "C#"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Python"))
        self.comboBox.setItemText(6, _translate("MainWindow", "Javascript"))
        self.comboBox.setItemText(7, _translate("MainWindow", "Pascal"))
        self.comboBox.setItemText(8, _translate("MainWindow", "FORTRAN"))
        self.comboBox.setItemText(9, _translate("MainWindow", "Haskell"))
        self.comboBox.setItemText(10, _translate("MainWindow", "Perl"))
        self.comboBox.setItemText(11, _translate("MainWindow", "Lisp"))
        self.comboBox.setItemText(12, _translate("MainWindow", "Matlab"))
        self.label.setText(_translate("MainWindow", "Language"))
        self.label_2.setText(_translate("MainWindow", "Basefile"))
        self.label_3.setText(_translate("MainWindow", "Add Text to Files"))
        self.label_4.setText(_translate("MainWindow", "Max Repititions"))
        self.checkBox.setText(_translate("MainWindow", "Directory"))
        self.label_5.setText(_translate("MainWindow", "Extracted Files"))
        self.label_6.setText(_translate("MainWindow", "Terminal"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSubmission.setTitle(_translate("MainWindow", "Submit"))
        self.menuReports.setTitle(_translate("MainWindow", "Reports"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionExtract_files.setText(_translate("MainWindow", "Extract files"))
        self.actionExtract_Files.setText(_translate("MainWindow", "Upload Zipped Folder"))
        self.actionGenerate_Reports.setText(_translate("MainWindow", "Generate Reports"))
        self.actionExtract_Files_2.setText(_translate("MainWindow", "Extract Files"))
        self.actionSave_Report.setText(_translate("MainWindow", "Save Report"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
